# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"lmap": "00_functional.ipynb",
         "lzip": "00_functional.ipynb",
         "lfilter": "00_functional.ipynb",
         "show_image": "01_images.ipynb",
         "show_images": "01_images.ipynb",
         "show_images_fpath": "01_images.ipynb",
         "show_titled_image": "01_images.ipynb",
         "flatfolder2dl": "02_fastdl.ipynb",
         "untar_fdrive": "03_datadownload.ipynb"}

modules = ["functional.py",
           "images.py",
           "fastdl.py",
           "datadownload.py"]

doc_url = "https://kessido.github.io/kesscore/"

git_url = "https://github.com/kessido/kesscore/tree/master/"

def custom_doc_links(name): return None
