# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"zip_cycle_longest": "00_functional.ipynb",
         "lmap": "00_functional.ipynb",
         "lzip": "00_functional.ipynb",
         "lfilter": "00_functional.ipynb",
         "lrange": "00_functional.ipynb",
         "Lmap": "00_functional.ipynb",
         "Lzip": "00_functional.ipynb",
         "Lfilter": "00_functional.ipynb",
         "Lrange": "00_functional.ipynb",
         "L.all": "00_functional.ipynb",
         "L.all_eq": "00_functional.ipynb",
         "isinstance": "00_functional.ipynb",
         "compose_star": "00_functional.ipynb",
         "is_not_close": "01_tests.ipynb",
         "test_not_close": "01_tests.ipynb",
         "L.assert_all_eq": "01_tests.ipynb",
         "test_all_eq": "01_tests.ipynb",
         "test_all": "01_tests.ipynb",
         "list_test_eq": "01_tests.ipynb",
         "test_eq": "01_tests.ipynb",
         "test_type": "01_tests.ipynb",
         "lshape": "02_tensor.ipynb",
         "Tensor.shape_is": "02_tensor.ipynb",
         "interleaved": "02_tensor.ipynb",
         "show_image": "03_images.ipynb",
         "show_images": "03_images.ipynb",
         "show_titled_image": "03_images.ipynb",
         "show_titled_images": "03_images.ipynb",
         "reproducibility": "04_random.ipynb",
         "RandomState": "04_random.ipynb",
         "RevGradFunc": "05_domainadaptation.ipynb",
         "RevGrad": "05_domainadaptation.ipynb",
         "revgrad": "05_domainadaptation.ipynb",
         "MultiActs": "06_mlp.ipynb",
         "Linear": "06_mlp.ipynb",
         "MLP": "06_mlp.ipynb",
         "try_extract": "07_download.ipynb",
         "download_drive": "07_download.ipynb",
         "download_general": "07_download.ipynb",
         "download_wget": "07_download.ipynb",
         "untar_drive": "07_download.ipynb",
         "untar_general": "07_download.ipynb",
         "untar_wget": "07_download.ipynb",
         "untar_dropbox": "07_download.ipynb"}

modules = ["functional.py",
           "tests.py",
           "tensor.py",
           "images.py",
           "random.py",
           "domainadaptation.py",
           "mlp.py",
           "download.py"]

doc_url = "https://kessido.github.io/kesscore/"

git_url = "https://github.com/kessido/kesscore/tree/master/"

def custom_doc_links(name): return None
