# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/08_contextmanagers.ipynb (unless otherwise specified).

__all__ = ['as_eval']

# Cell
from .base import *

# Cell
@contextmanager
def as_eval(model):
    if model.training:
        try:     yield model.eval()
        finally: model.train()
    else: yield model