# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_datadownload.ipynb (unless otherwise specified).

__all__ = ['untar_fdrive']

# Cell
from .imports import *
import warnings

# Cell
def untar_fdrive(fid, fname, destfold, extract_func=file_extract):
    'download https://drive.google.com/uc?id={fid} to destfold/fname.tar.gz and extract it to destfold/fname. Will not download if folder exist.'
    destfold=Path(destfold)
    if (destfold/fname).exists():
        warnings.warn('Folder already exist, so will not download again: ' + str(destfold/fname))
    else:
        import gdown
        path=gdown.download(f'https://drive.google.com/uc?id={fid}', str(destfold/f'{name}.tar.gz'))
        file_extract(path)
        Path(path).unlink()
    return destfold/fname