# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_domainadaptation.ipynb (unless otherwise specified).

__all__ = ['RevGradFunc', 'RevGrad', 'revgrad']

# Cell
from .imports import *

# Cell
class RevGradFunc(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x): ctx.save_for_backward(x); return x
    @staticmethod
    def backward(ctx, grad_output): return -grad_output if ctx.needs_input_grad[0] else None

revgrad = RevGradFunc.apply

class RevGrad(nn.Module):
    def forward(self, x): return revgrad(x)