# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_fastdl.ipynb (unless otherwise specified).

__all__ = ['flatfolder2dl']

# Cell
from .imports import *

# Cell
@delegates(ImageDataLoaders.from_lists, but=('path','fnames','labels'))
def flatfolder2dl(path, get_y=noop, **kwargs):
    return ImageDataLoaders.from_lists(path='/',fnames=path.ls(),labels=path.ls().map(get_y),**kwargs)