# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_functional.ipynb (unless otherwise specified).

__all__ = []

# Cell
from .imports import *
from functools import wraps

# Cell
def _listify(f=None):
    if f==None: return lisitify_decorator
    @wraps(f)
    def _inner(*args, **kwargs): return list(f(*args, **kwargs))
    return _inner

# Cell
lmap,lzip,lfilter = map(_listify,[map,zip,filter])