# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_images.ipynb (unless otherwise specified).

__all__ = ['show_image', 'show_images', 'show_images_fpath', 'show_titled_image']

# Cell
from .imports import *

# Cell
def _load_image(im): return load_image(im) if isinstance(im, (str, Path)) else im

_show_image = show_image
@delegates(_show_image)
def show_image(im, **kwargs): return _show_image(_load_image(im), **kwargs)

_show_images = show_images
@delegates(_show_images)
def show_images(ims, **kwargs): return _show_images(L(ims).map(_load_image), **kwargs)

@delegates(show_images)
def show_images_fpath(img_paths:list, **kwargs):
    if 'titles' not in kwargs: kwargs['titles'] = img_paths
    return show_images(img_paths, **kwargs)

_show_titled_image = show_titled_image
@delegates(_show_titled_image)
def show_titled_image(o, **kwargs):
    if isinstance(o, (str,Path)): o = (o, o)
    o = (_load_image(o[0]), *o[1:])
    return _prev_show_titled_image(o)