# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/10_modules.ipynb (unless otherwise specified).

__all__ = ['device']

# Cell
#exports
from .base import *

# Cell
@patch(as_prop=True)
def device(self:nn.Module): return next(self.parameters()).device