# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09_plots.ipynb (unless otherwise specified).

__all__ = ['plot_func']

# Cell
#exports
from .base import *

# Cell
def plot_func(f, start, stop, num, logscalex=False, logscaley=False, figsize=(15,3), xlimit=None, ylimit=None):
    plt.figure(figsize=figsize)
    if logscalex: x = np.logspace(start,stop,num,endpoint=True)
    else:         x = np.linspace(start,stop,num,endpoint=True)

    y = [f(x1) for x1 in x]
    if logscalex: plt.xscale('log')
    if logscaley: plt.yscale('log')
    plt.plot(x,y)

    if xlimit is not None: plt.xlim(*xlimit)
    if ylimit is not None: plt.ylim(*ylimit)