# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/07_tests.ipynb (unless otherwise specified).

__all__ = ['is_not_close', 'test_not_close']

# Cell
from .imports import *

# Cell
def is_not_close(a,b,eps=1e-5):
    "Is `a` not within `eps` of `b`"
    return not is_close(a,b,eps)
def test_not_close(a,b,eps=1e-5):
    "`test` that `a` is not within `eps` of `b`"
    test(a,b,partial(is_not_close,eps=eps),f'close [{eps=}]')